### ISSUE TITLE
Release to Rubygems?

### ISSUE THREAD

**Issue by jellybob** [aars/rack-bodyparser#1]
We've found this library and would like to use it for a project in development, but I'm a little uneasy having to depend directly on master from git, is there any chance you could do a release to Rubygems (or even just tag the current version)?

**Comment by aars** [comment]
Good point! I will release this on Rubygems somewhere this week.

**Comment by aars** [comment]
@jellybob Released! https://rubygems.org/gems/rack-bodyparser

**Comment by aars** [comment]
This is my first published Gem, if there is anything I can do to improve this release, please let me know!
